DROP DATABASE IF EXISTS CREATE DATABASE employee;

CREATE DATABASE employee;

USE employee;

CREATE TABLE department (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
)

CREATE TABLE role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INT
)

SELECT * FROM ;